# Site Configs
name: Ionic Framework
timezone: "US/Central"
highlighter: rouge
url: https://ionicframework.com

source: content

defaults:
  -
    values:
      layout: "fluid/default"

exclude: [node_modules, scss, README.md, Gulpfile.js]

# Markdown Settings
markdown: kramdown
kramdown:
  toc_levels: 2..3
  input: GFM
  hard_wrap: false


# Legacy Vars

# Default news if the page didnt enter news
news: Check out our <a href="/docs/guide/">Guide</a>, which covers all the basics of setting up.
v2news: Check out our <a href="/docs/guide/">Guide</a>, which covers all the basics of setting up.

# Latest Version Config
latest_download: http://code.ionicframework.com/1.3.3/ionic-v1.3.3.zip
latest_version: 1.3.3 "germany"
latest_release_date: 2017-02-24

# Which version of AngularJS the latest build includes
included_angular_version: 1.4.3

# Which active Cordova version we recommend
recommended_cordova_version: 5.1.1

# the primary plunkr to fork
code_sample_base_url: http://plnkr.co/edit/vD0O9M?p=preview
